data_dir: "../data/raw"
index_dir: "../data/index"

embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
embedding_device: "cuda"
enable_context: True

chunk_size: 2048
chunk_overlap: 64
top_k: 5

llm_host: "http://ollama:11434"
llm_model: "llama3:latest"
temperature: 0
max_tokens: 1024

log_level: "DEBUG"
