# Directories
data_dir: "/src/data/raw"
index_dir: "/src/data/index"
embed_dir: "/emb_models"
log_dir: "/logs"

# Chunking
chunking_strategy: "simple"  # simple | structure
chunk_size: 512
chunk_overlap: 64

# Embedding
embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
embedding_device: "cuda"
normalize_embeddings: True

# Index Parameters (chroma)
hnsw_ef_construction: 100
hnsw_ef_search: 100
hnsw_max_neighbors: 16

# Retrieval
top_k: 5

# Post-Retrieval
metadata_filter: False
metadata_enhancement: False
post_bm25_rerank: False
simularity_threshold: 3.0

# Generation
llm_host: "http://ollama:11434"
llm_model: "llama3:8b"
temperature: 0.0
max_tokens: 512

# Misc
log_level: "INFO"
